language: node_js
node_js:
  - "node"
script: yarn build
before_deploy: ls -al
deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_ACCESS_KEY"
  region: "$AWS_EB_REGION"  
  app: "$AWS_EB_APP"
  env: "$AWS_EB_ENV"
  bucket_name: "$AWS_S3_EB_BUCKET"
  on:
    branch: master