language: node_js
node_js:
  - "node"
script:
  - yarn typescript
  - yarn check-format
  - yarn lint
  - yarn build
deploy:
  provider: script
  before_script:
  # See https://travis-ci.org/JustUtahCoders/comunidades-unidas-internal/builds/647606213 for python3 explanation
  script: ls -al && echo "Deploying with ebcli" && virtualenv -p /opt/pyenv/shims/python3 p3 && source p3/bin/activate && pip install awsebcli && eb deploy comunidades-unidas-internal-prod
  on:
    branch: master
  skip_cleanup: true
