language: node_js
node_js:
  - "node"
script:
  - yarn typescript
  - yarn check-format
  - yarn lint
  - yarn build
before_deploy: 
  - pip install awsebcli --user
  - ls -al
deploy:
  provider: script
  before_script:
  script: echo "Deploying with ebcli" && eb deploy comunidades-unidas-internal-prod
  on:
    branch: master
  skip_cleanup: true