language: node_js
node_js:
  - "node"
script: yarn build
before_deploy: 
  - pip install awsebcli --user
  - ls -al
  - git status
  - git checkout master
deploy:
  provider: script
  script:
    - ebcli deploy --staged
  on:
    branch: master