language: node_js
node_js:
  - "node"
script: yarn build
before_deploy: 
  - ls -al
  - pip install awsebcli
deploy:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  script:
    - ebcli deploy
  on:
    branch: master