language: node_js
node_js:
  - "node"
script: yarn build
before_deploy: 
  - pip install awsebcli --user
  - git status
  - ls -al
deploy:
  provider: script
  before_script:
  script: echo "Deploying with ebcli" && eb deploy test-env
  on:
    branch: master
  skip_cleanup: true