language: node_js
node_js:
  - "node"
script:
  - yarn typescript
  - yarn check-format
  - yarn lint
  - yarn build
before_deploy:
  # See https://travis-ci.org/JustUtahCoders/comunidades-unidas-internal/builds/647606213
  - virtualenv -p /opt/pyenv/shims/python3 p3 && source p3/bin/activate && python --version && pip --version && pip install awsebcli
  - ls -al
deploy:
  provider: script
  before_script:
  script: echo "Deploying with ebcli" && source p3/bin/activate && python --version && eb deploy comunidades-unidas-internal-prod
  on:
    branch: master
  skip_cleanup: true
