language: node_js
node_js:
  - "node"
script: yarn build
before_deploy: 
  - pip install awsebcli --user
deploy:
  skip_cleanup: true
  provider: script
  script:
    - git status
    - ls -al
    - ebcli deploy --staged
  on:
    branch: master