language: node_js
node_js:
  - "node"
script:
  - yarn typescript
  - yarn check-format
  - yarn lint
  - yarn build
before_deploy:
  # See https://travis-ci.org/JustUtahCoders/comunidades-unidas-internal/builds/647606213
  - which python3
  - alias pip=pip3
  - alias python=python3
  - python --version
  - pip --version
  - pip install awsebcli --user
  - ls -al
deploy:
  provider: script
  before_script:
  script: alias pip=pip3 && alias python=python3 && echo "Deploying with ebcli" && eb deploy comunidades-unidas-internal-prod
  on:
    branch: master
  skip_cleanup: true
