language: node_js
node_js:
  - "node"
script:
  - yarn typescript
  - yarn check-format
  - yarn lint
  - yarn build
before_deploy:
  # See https://travis-ci.org/JustUtahCoders/comunidades-unidas-internal/builds/647606213
  # and https://stackoverflow.com/questions/43267157/python-attributeerror-module-object-has-no-attribute-ssl-st-init
  - pip uninstall pyopenssl
  - pip install pyopenssl

  - pip install awsebcli --user
  - ls -al
deploy:
  provider: script
  before_script:
  script: echo "Deploying with ebcli" && eb deploy comunidades-unidas-internal-prod
  on:
    branch: master
  skip_cleanup: true
