language: node_js
node_js:
  - "node"
script: yarn build
before_deploy: 
  - pip install awsebcli --user
deploy:
  provider: script
  before_script:
    - git status
    - ls -al
  script: ebcli deploy --staged
  on:
    branch: master
  skip_cleanup: true