language: node_js
node_js:
  - "node"
script:
  - yarn typescript
  - yarn check-format
  - yarn lint
  - yarn build
  - touch static/need-to-gzip.txt
before_deploy:
  # gzip frontend files
  - if test -f static/need-to-gzip.txt; then find static -type f -exec gzip -9 {} \; -exec mv {}.gz {} \; fi
  # See https://travis-ci.org/JustUtahCoders/comunidades-unidas-internal/builds/647606213
  - if test -f static/need-to-gzip.txt; then virtualenv -p /opt/pyenv/shims/python3 p3 && source p3/bin/activate && python --version && pip --version && pip install awsebcli fi
  - ls -al
  - rm static/need-to-gzip.txt
deploy:
  - provider: s3
    bucket: comunidades-unidas-frontend-assets
    skip_cleanup: true
    acl: public_read
    region: us-west-2
    local_dir: static
    cache_control: "max-age=31536000"
    detect_encoding: true
    default_text_charset: "utf-8"
    on:
      branch: master
  - deploy:
    provider: script
    before_script:
    script: echo "Deploying with ebcli" && python --version && eb deploy comunidades-unidas-internal-prod
    on:
      branch: master
    skip_cleanup: true
